search_space:
  dropout:
    - 0.1
    - 0.3
  lr:
    - 0.001
    - 0.0005

fixed_params:
  batch_size: 32
  weight_decay: 0.01
  scheduler_patience: 3
  scheduler_factor: 0.1
  max_epochs: 100
  early_stopping_patience: 5
  num_classes: 6
  seed: 42
